### ISSUE TITLE
Container cost/benefit trade-off

### ISSUE THREAD

**Issue by mbhall88** [johanneskoester/scipaper-snakemake-2020#10]
https://github.com/johanneskoester/scipaper-snakemake-2020/blob/54b455a5a8b4c97824e1d5c73dfd60b2eedb0317/main.tex#L286-L288

The paper is great and my *only* qualm is this small section about container integration.  

On the one hand, we say that containers use a lot of storage an effort. Yet, we go on to say that the "sweet spot" is using both containers and conda without explaining how this might alleviate the downsides of containers just mentioned in the previous sentences.  

It might be clarifying to add a sentence explaining that when using them together in this way, we generally just use a single container, something like a "base" that just contains conda, and thus negate the large storage requirements and container modification, but gain control over the operating system and associated execution environment.

**Comment by tomkinsc** [comment]
This is a good point. Part of the benefit of containers is layering though, so maybe we say something like:

> The downside of using containers is that generating and modifying container images requires additional effort, as well as storage, since the image has to be uploaded to a container registry. The storage needed for containers can be minimized during workflow execution by reusing a common container image across multiple workflow steps, or by using step-specific containers derived from common base layer with smaller subsequent layers containing step-specific customizations.

**Comment by johanneskoester** [comment]
Awesome, thank you @tomkinsc and @mbhall88!
